### ISSUE TITLE
[linux][ubuntu] rtthread 带有submodule的软件包在linux下面下载不了pkgs --update 不下来

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/supperthomas_doc#248]

**Comment by supperthomas** [comment]
```

Submodule 'jerryscript' (https://github.com/jerryscript-project/jerryscript.git) registered for path 'jerryscript'
Cloning into '/root/rt-thread/bsp/qemu-vexpress-a9/packages/jerryscript-latest/jerryscript'...
Traceback (most recent call last):
  File "/root/.env/tools/scripts/env.py", line 126, in <module>
    main()
  File "/root/.env/tools/scripts/env.py", line 122, in main
    args.func(args)
  File "/root/.env/tools/scripts/cmds/cmd_package/__init__.py", line 42, in run_env_cmd
    package_update()
  File "/root/.env/tools/scripts/cmds/cmd_package/cmd_package_update.py", line 831, in package_update
    if not install_packages(sys_value, force_update):
  File "/root/.env/tools/scripts/cmds/cmd_package/cmd_package_update.py", line 781, in install_packages
    if install_package(env_root, pkgs_root, bsp_root, package, force_update):
  File "/root/.env/tools/scripts/cmds/cmd_package/cmd_package_update.py", line 285, in install_package
    if not install_git_package(bsp_package_path, pkgs_name_in_json, package_info, package_url, ver_sha,
  File "/root/.env/tools/scripts/cmds/cmd_package/cmd_package_update.py", line 184, in install_git_package
    if len(replace_list):
TypeError: object of type 'NoneType' has no len()
```

**Comment by supperthomas** [comment]
https://github.com/RT-Thread/env/blob/master/cmds/cmd_package/cmd_package_update.py
这里有个小bug

**Comment by supperthomas** [comment]
done
